Make some navigation classes and methods public for extended usability
maplibre/maplibre-navigation-android pull request #112
Opened 2024-07-03 16:18 UTC by BackPackerDz

This PR updates the access modifiers of `ViewRouteListener` and `NavigationViewRouter`, along with three of its methods (`findRouteFrom`, `updateLocation`, `updateCurrentRoute`), to public. These changes are essential to allow developers to handle rerouting more directly within their applications. Without these modifications, developers are forced to rely on less desirable solutions such as duplicating internal code or employing fragile workarounds. Making these classes and methods public simplifies the development process and enhances the flexibility of the navigation functionality.

I welcome feedback on these changes and am open to discussing alternative approaches. Please share any suggestions or insights you have.

Several useful classes in the library are internal, limiting their direct usability. I’d appreciate insights into the decision for such accessibility settings to align our development efforts better.

2024-07-27 13:55 UTC, boldtrn commented on .github/workflows/publish_library.yaml
What is this change about? Where does this release to?

2024-07-27 13:56 UTC, boldtrn requested changes
I don't mind changing some methods or classes to public to help with overwriting certain features. I am not sure about the publishing script. @Fabi755 do you have an any other input on this?

2024-07-28 07:28 UTC, BackPackerDz commented on .github/workflows/publish_library.yaml
My apologies, I didn't notice that pushing to our own fork also updated this branch.

2024-08-12 14:19 UTC, boldtrn approved these changes
LGTM 👍

2024-08-12 14:19 UTC, merged